[workspace]
resolver = "2"

members = [
    "plprql",
    "plprql-tests"
]

[profile.dev]
panic = "unwind"
debug = true

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "debuginfo"

[workspace.dependencies]
pgrx = "=0.12.9"
pgrx-tests = "=0.12.9"
