name: PL/PRQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "false"

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # ubuntu-latest comes with PostgreSQL 14 pre-installed
    - name: Install PostgreSQL headers
      run: sudo apt-get install libpq5=14
    - name: Install cargo-pgrx
      run: cargo install --locked --version=0.11.2 cargo-pgrx --debug --force
    - name: Init pgrx
      run: cargo pgrx init --pg14 /usr/bin/pg_config
    - name: Install extension
      run: cargo pgrx install
    - name: Build package
      run: cargo pgrx package
