name: Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 7 * * MON-FRI'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "false"

jobs:
  Deb:
    if: false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # We want all of them to run, even if one fails
      matrix:
        pg: [ "12", "13", "14", "15", "16" ]
        os: [ "debian" ]
    steps:
      - uses: actions/checkout@v4
      - name: Package PL/PRQL for PostgreSQL ${{ matrix.pg }} (${{ matrix.os }})
        shell: bash
        run: |
          docker build --build-arg PG_MAJOR_VERSION="${{ matrix.pg }}" -t plprql -f ".github/docker/Dockerfile.${{ matrix.os }}" .
          docker run plprql cargo test --no-default-features --features "pg${{ matrix.pg }}"
  Bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL headers
        run: sudo apt-get install postgresql-server-dev-14
      - name: Install cargo-pgrx
        run: |
          PGRX_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[]|select(.name=="pgrx")|.version')
          cargo install --locked --version=$PGRX_VERSION cargo-pgrx --debug --force
          cargo pgrx init --pg14 $(which pg_config)
      - name: Run install.sh
        run: |
          cd scripts
          chmod +x install.sh
          ./install.sh
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          # superuser (-s), can create databases (-d) and roles (-r), no password prompt (-w) named runner
          sudo -u postgres createuser -s -d -r -w runner
      - name: Verify install
        run: |
          createdb -U runner runner
          psql -U runner -c "create extension plprql;"
          psql -U runner -c "select prql_to_sql('from table');"
