name: PL/PRQL

on:
  # schedule:
  #   - cron: '0 7 * * MON-FRI'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "false"

jobs:
  distro_tests:
    name: Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # We want all of them to run, even if one fails
      matrix:
        pg: [ "12" ] # ["12", "13", "14", "15", "16"]
        container: [ "debian" ]
    steps:
      - uses: actions/checkout@v3
      - name: Package PL/PRQL for PostgreSQL ${{ matrix.pg_version }} (${{ matrix.container }})
        shell: bash
        run: |
          docker build --build-arg PG_MAJOR_VER="${{ matrix.pg_version }}" -t plprql -f ".github/docker/Dockerfile.${{ matrix.container }}" .
          docker run pgrx cargo test --no-default-features --features "pg${{ matrix.pg_version }}"
